const toys = [
    { id: 1, name: "HG GUNDAM AERIAL REBUILD", image: "images/toys/Aerial.jpg", price: 590, description: "Bandai® Gundam Gunpla High Grade Plastic Model Kits Series HG XVX-016RN GUNDAM AERIAL REBUILD The repaired version of the Gundam Aerial from Mobile Suit Gundam: The Witch from Mercury.", type: 'toy', DATE: '2024-10-07' },
    { id: 2, name: "PG RX-0 UNICORN GUNDAM", image: "images/toys/PG_Unicorn.webp", price: 6800, description: "Bandai® Gunpla Perfect Grade 1/60 Model Kit PG RX-0 UNICORN GUNDAM", type: 'toy', DATE: '2024-10-07'  },
    { id: 3, name: "PG GUNDAM EXIA", image: "images/toys/exia.jpg", price: 6490, description: "Bandai® Gunpla Perfect Grade 1/60 Model Kit PG GN-001 GUNDAM EXIA", type: 'toy', DATE: '2024-10-07'  },
    { id: 4, name: "MG MS-06R ZAKU II HIGH MOBILITY TYPE PSYCHO ZAKU VER KA", image: "images/toys/psycho_zaku.jpg", price: 2790, description: "Bandai® Gunpla Master Grade 1/100 VER KA Model Kit MG MS-06R ZAKU II HIGH MOBILITY TYPE PSYCHO ZAKU VER KA", type: 'toy', DATE: '2024-10-07'  },
    { id: 5, name: "HG-GQ GQUUUUUUX", image: "images/toys/gquuuuuux.jpg", price: 760, description: `"Mobile Suit Gundam GQuuuuuuX," a brand-new "Gundam" movie and TV series, will make its debut shortly -- and now you can add the GQuuuuuuX itself to your collection! Bandai's newest "High Grade (HG)" model kit faithfully reproduces the new Gundam's distinctive form; it's loaded with articulation in the torso, hips, and elsewhere for dynamic posability after assembly! The backpack is flexible and can be displayed at various angles, and a wide variety of weapons are included too. Order yours today!`, type: 'toy', DATE: '2025-05-22' },
    { id: 6, name: "S.H.Figuarts Honkai: Star Rail SAM Action Figure", image: "images/toys/sam.webp", price: 4999, description: `“Like fyreflies to a flame… life begets death.”`, type: 'toy', DATE: '2025-05-22' },
    { id: 7, name: "(BSF) WARHAMMER 40000: INTRODUCTORY SET (ENG)", image: "images/toys/wh40000is.jpg", price: 2450, description: "A great way to begin your journey into the Warhammer 40,000 hobby. Includes everything you need to start playing the legendary tabletop game.", type: 'toy', DATE: '2024-10-07'  },
    { id: 8, name: "Warhammer 40k: Adeptus Custodes: Allarus Custodians", image: "images/toys/whc.jpg", price: 2150, description: "Adeptus Custodes miniatures from the Warhammer 40k universe, highly detailed for collectors and gamers alike.", type: 'toy', DATE: '2024-10-07'  },
    { id: 9, name: "Honkai: Star Rail Qingque 1/10 Figure", image: "images/toys/QQ.jpg", price: 1190, description: "A detailed 1/10 scale figure of Qingque from Honkai: Star Rail.", type: 'toy', DATE: '2024-10-07' },
    { id: 10, name: "Plarail Bullet Train N700S Basic Set", image: "images/toys/N700.jpg", price: 2150, description: "All-in- one set for those who want to start Plarail with [Shinkansen N700S]!", type: 'toy', DATE: '2024-10-07'  },
    { id: 11, name: "Tetris wood puzzle", image: "images/toys/Tetris.jpg", price: 159, description: "A wooden puzzle based on the classic Tetris game. Perfect for brain training and a stylish decorative piece.", type: 'toy', DATE: '2024-10-07'  },
    { id: 12, name: "Catan [EN]", image: "images/toys/Catan.jpg", price: 669, description: "The Settlers of Catan board game, a strategy game where players collect resources and build roads and settlements.", type: 'toy', DATE: '2024-10-07'  }
];

const games = [
    { id: 1, name: "Warhammer 40,000: Space Marine 2", image: "images/games/sm2.jpg", price: 1490, description: "Embody the superhuman skill and brutality of a Space Marine. Unleash deadly abilities and devastating weaponry to obliterate the relentless Tyranid swarms. Defend the Imperium in spectacular third-person action in solo or multiplayer modes.", type: 'game', DATE: '2024-10-07' },
    { id: 2, name: "HELLDIVERS™ 2", image: "images/games/hd2.jpg", price: 1290, description: "HELLDIVERS™ 2 is a 3rd person squad-based shooter that sees the elite forces of the Helldivers battling to win an intergalactic struggle to rid the galaxy of the rising alien threats.", type: 'game', DATE: '2024-10-07' },
    { id: 3, name: "ELDEN RING", image: "images/games/edl.jpg", price: 1790, description: "The Lands Between are part of a vast continent where magnificent open fields and huge dungeons with complex and three-dimensional designs are seamlessly connected. As you explore, the joy of discovering unknown and overwhelming threats awaits you.", type: 'game' },
    { id: 4, name: "NieR:Automata™", image: "images/games/Nier_Automata.jpg", price: 1390, description: "NieR: Automata tells the story of androids 2B, 9S and A2 and their battle to reclaim the machine-driven dystopia overrun by powerful machines. Humanity has been driven from the Earth by mechanical beings from another world. In a final effort to take back the planet, the human resistance sends a force of android soldiers to destroy the invaders. Now, a war between machines and androids rages on... A war that could soon unveil a long-forgotten truth of the world.", type: 'game', DATE: '2024-10-07' },
    { id: 5, name: "NieR Replicant™ ver.1.22474487139...", image: "images/games/Nier_Replicant.jpg", price: 1990, description: "A thousand-year lie that would live on for eternity... NieR Replicant ver.1.22474487139... is an updated version of NieR Replicant, previously only released in Japan. Discover the one-of-a-kind prequel to the critically-acclaimed masterpiece NieR:Automata. Now with a modern upgrade, experience masterfully revived visuals, a fascinating storyline and more! ", type: 'game', DATE: '2024-10-07' },
    { id: 6, name: "Cyberpunk 2077", image: "images/games/Cyberpunk.jpg", price: 1799, description: "Cyberpunk 2077 is an open-world, action-adventure RPG set in the megalopolis of Night City, where you play as a cyberpunk mercenary wrapped up in a do-or-die fight for survival.", type: 'game', DATE: '2024-10-07' },
    { id: 7, name: "DARK SOULS™ III", image: "images/games/dsIII.jpg", price: 1500, description: "The third and final chapter of the Dark Souls series, As fires fade and the world falls into ruin, journey into a universe filled with more colossal enemies and environments. Players will be immersed into a world of epic atmosphere and darkness through faster gameplay and amplified combat intensity. ", type: 'game', DATE: '2024-10-07' },
    { id: 8, name: "Cities: Skylines", image: "images/games/cs1.jpg", price: 819, description: "Cities: Skylines is a modern take on the classic city simulation. The game introduces new game play elements to realize the thrill and hardships of creating and maintaining a real city whilst expanding on some well-established tropes of the city building experience. You’re only limited by your imagination, so take control and reach for the sky!", type: 'game', DATE: '2024-10-07' },
    { id: 9, name: "Stellaris", image: "images/games/Stellaris.jpg", price: 1089, description: "Get ready to explore, discover and interact with a multitude of species as you journey among the stars. Forge a galactic empire by sending out science ships to survey and explore, while construction ships build stations around newly discovered planets. Discover buried treasures and galactic wonders as you spin a direction for your society, creating limitations and evolutions for your explorers. Alliances will form and wars will be declared.", type: 'game', DATE: '2024-10-07' },
    { id: 10, name: "Stellaris: Apocalypse", image: "images/games/St_Apo.jpg", price: 669, description: "Stellaris: Apocalypse is a full expansion which redefines stellar warfare for all players with a host of new offensive and defensive options. Destroy entire worlds with terrifying new planet-killer weapons, fight against (or alongside) ruthless space pirates, and maybe discover a few non-violent game features as well.", type: 'StellarisDLC', DATE: '2024-10-07' },
    { id: 11, name: "Cities: Skylines II", image: "images/games/cs2.webp", price: 1359, description: "Raise a city from the ground up and transform it into a thriving metropolis with the most realistic city builder ever. Push your creativity and problem-solving to build on a scale you've never experienced. With deep simulation and a living economy, this is world-building without limits.", type: 'game', DATE: '2025-05-22' },
    { id: 12, name: "PC Building Simulator", image: "images/games/PCbS1.jpg", price: 400, description: "Build and grow your very own computer repair enterprise as you learn to diagnose, fix and build PCs. With real-world licensed components and comprehensive hardware and software simulation, you can plan and bring your ultimate PC to life.", type: 'game', DATE: '2025-05-22' },
    { id: 13, name: "PC Building Simulator 2", image: "images/games/PCbS2.jpg", price: 625, description: "Grow your empire as you learn to repair, build and customize PCs at the next level. Experience deeper simulation, an upgraded career mode, and powerful new customisation features. Use realistic parts from 40+ hardware brands to bring your ultimate PC to life.", type: 'game', DATE: '2025-05-22' },
    { id: 14, name: "Need for Speed™ Heat", image: "images/games/nfsh.jpg", price: 1899, description: "A thrilling race experience pits you against a city’s rogue police force as you battle your way into street racing’s elite. Hustle by day and risk it all at night in Need for Speed™ Heat, a white-knuckle street racer, where the lines of the law fade as the sun starts to set.", type: 'game', DATE: '2025-05-22' },
    { id: 15, name: "Left 4 Dead 2", image: "images/games/l4d2.jpg", price: 220, description: "Set in the zombie apocalypse, Left 4 Dead 2 (L4D2) is the highly anticipated sequel to the award-winning Left 4 Dead, the #1 co-op game of 2008. This co-operative action horror FPS takes you and your friends through the cities, swamps and cemeteries of the Deep South, from Savannah to New Orleans across five expansive campaigns.", type: 'game', DATE: '2025-05-22' },
    { id: 16, name: "Devil May Cry 5", image: "images/games/DMC5.jpg", price: 919, description: "The ultimate Devil Hunter is back in style, in the game action fans have been waiting for.", type: 'game', DATE: '2025-05-22' },
    { id: 17, name: "METAL GEAR RISING: REVENGEANCE", image: "images/games/MGRR.webp", price: 499, description: "Developed by Kojima Productions and PlatinumGames, METAL GEAR RISING: REVENGEANCE takes the renowned METAL GEAR franchise into exciting new territory with an all-new action experience. The game seamlessly melds pure action and epic story-telling that surrounds Raiden – a child soldier transformed into a half-human, half-cyborg ninja who uses his High Frequency katana blade to cut through any thing that stands in his vengeful path!", type: 'game', DATE: '2025-05-22' },
    { id: 18, name: "Forza Horizon 5", image: "images/games/FH5.webp", price: 1899, description: "Explore the vibrant open world landscapes of Mexico with limitless, fun driving action in the world’s greatest cars.", type: 'game', DATE: '2025-05-22' },
    { id: 19, name: "Kerbal Space Program", image: "images/games/kbs1.jpg", price: 729, description: "In Kerbal Space Program, take charge of the space program for the alien race known as the Kerbals. You have access to an array of parts to assemble fully-functional spacecraft that flies (or doesn’t) based on realistic aerodynamic and orbital physics.", type: 'game', DATE: '2025-05-22' },
    { id: 20, name: "RimWorld", image: "images/games/rw.jpg", price: 550, description: "A sci-fi colony sim driven by an intelligent AI storyteller. Generates stories by simulating psychology, ecology, gunplay, melee combat, climate, biomes, diplomacy, interpersonal relationships, art, medicine, trade, and more.", type: 'game', DATE: '2025-05-22' },
    { id: 21, name: "Factorio", image: "images/games/factorio.jpg", price: 700, description: "Factorio is a game about building and creating automated factories to produce items of increasing complexity, within an infinite 2D world. Use your imagination to design your factory, combine simple elements into ingenious structures, and finally protect it from the creatures who don't really like you.", type: 'game', DATE: '2025-05-22' },
    { id: 22, name: "Raft", image: "images/games/raft.webp", price: 369, description: "Raft™ throws you and your friends into an epic oceanic adventure! Alone or together, players battle to survive a perilous voyage across a vast sea! Gather debris, scavenge reefs and build your own floating home, but be wary of the man-eating sharks!", type: 'game', DATE: '2025-05-22' },
    { id: 23, name: "Subnautica", image: "images/games/subnau.jpg", price: 856, description: "Descend into the depths of an alien underwater world filled with wonder and peril. Craft equipment, pilot submarines and out-smart wildlife to explore lush coral reefs, volcanoes, cave systems, and more - all while trying to survive.", type: 'game', DATE: '2025-05-22' },
    { id: 24, name: "Terraria", image: "images/games/terraria.jpg", price: 220, description: "Dig, fight, explore, build! Nothing is impossible in this action-packed adventure game. Four Pack also available!", type: 'game', DATE: '2025-05-22' },
    { id: 25, name: "Portal", image: "images/games/portal.jpg", price: 220, description: "Portal™ is a new single player game from Valve. Set in the mysterious Aperture Science Laboratories, Portal has been called one of the most innovative new games on the horizon and will offer gamers hours of unique gameplay.", type: 'game', DATE: '2025-05-22' }
];

const allProducts = [...toys, ...games];

const bestSellers = [
    games[3],
    toys[4],
    games[20],
    toys[2],
    games[4]
];

const CarouselItem = [
    games[15],
    games[3],
    toys[0],
    toys[1],
    games[12]
];

export { toys, games, allProducts, bestSellers, CarouselItem };